# Pre-release version number
version: v1.5

website:
  title: "Quarto (Pre-release)"
  image: "quarto-dark-bg-pre.jpeg"
  site-url: https://prerelease.quarto.org
  repo-branch: prerelease
  announcement:
    dismissable: false
    content: "Pre-release ({{< meta version >}}) Documentation: [Download {{< meta version >}}](/docs/download/prerelease.qmd), [Current Release Docs](http://quarto.org) "
  navbar:
    pinned: true
  search:
    algolia:
      index-name: prerelease_QUARTO

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss, theme-prerelease-docs.scss]
