project:
  type: site
  output-dir: _site
resources: 
  - "/docs/download/_download.json"
site:
  title: "Quarto"
  image: "quarto.png"
  google-analytics: "G-FV9Z7SDZ0M"
  open-graph: true
  twitter-card: true
  site-url: https://quarto.org
  repo-url: https://github.com/quarto-dev/quarto-web
  repo-actions: [edit, issue]
  page-navigation: true
  search:
    algolia:
      index-name: prod_QUARTO
      application-id: RHB655RP2G
      search-only-api-key: 184556c7b323fe51ecefb18d9c172e3c
      analytics-events: true
  footer: 
    left: |
      [![Search By Algolia](/search-by-algolia.png){.search-attribution}](http://www.algolia.com/)

  navbar:
    background: light
    logo: quarto.png
    title: false
    collapse-below: lg
    sidebar-menus: true
    
    right:
      - sidebar:get-started
      - sidebar:using
      - sidebar:formats
      - sidebar:projects
      - href: docs/gallery/index.qmd
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
    
  sidebar:
    - id: get-started
      title: "Get Started"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - section: "Get Started"
          contents:
            - text: "Welcome"
              href: index.qmd
            - docs/getting-started/installation.qmd
            - docs/getting-started/quarto-basics.qmd
            - docs/getting-started/running-code.qmd
        - section: "Code Editors"
          contents:
            - docs/tools/jupyter-lab.qmd
            - docs/tools/rstudio.qmd
            - docs/tools/vscode.qmd
            - docs/tools/text-editors.qmd
        - section: "Visual Editor"
          contents:
            - text: Editor Basics
              href: docs/visual-editor/index.qmd 
            - docs/visual-editor/technical.qmd
            - docs/visual-editor/content.qmd
            - docs/visual-editor/options.qmd
            - docs/visual-editor/markdown.qmd
          
    - id: using
      title: "Using"
      contents:
        - section: "Authoring"
          contents:
            - docs/authoring/markdown-basics.qmd
            - docs/authoring/footnotes-and-citations.qmd
            - docs/authoring/figures-and-layout.qmd
            - docs/authoring/cross-references.qmd
            - docs/authoring/callouts.qmd
            - docs/authoring/page-layout.qmd
            - docs/authoring/shortcodes-and-filters.qmd
            - docs/authoring/language.qmd
        - section: "Computations"
          contents:
            - docs/computations/running-code.qmd
            - docs/computations/execution-options.qmd
            - docs/computations/parameters.qmd
        - section: "Interactive Docs"
          contents:
            - text: "Overview"
              href: docs/interactive/index.qmd
            - section: docs/interactive/ojs/index.qmd
              contents:
                - text: "Introduction"
                  href: docs/interactive/ojs/index.qmd
                - docs/interactive/ojs/libraries.qmd
                - docs/interactive/ojs/data-sources.qmd
                - docs/interactive/ojs/ojs-cells.qmd
                - docs/interactive/ojs/shiny.qmd
                - docs/interactive/ojs/code-reuse.qmd
                - section: "Examples"
                  contents:
                    - docs/interactive/ojs/examples/penguins.qmd
                    - docs/interactive/ojs/examples/sunburst.qmd
                    - docs/interactive/ojs/examples/arquero.qmd
                    - docs/interactive/ojs/examples/population.qmd
                    - docs/interactive/ojs/examples/noaa-co2.qmd
                    - docs/interactive/ojs/examples/github.qmd
                    - docs/interactive/ojs/examples/layout.qmd
                    - section: "Shiny"
                      contents:
                        - text: "K-Means"
                          href: https://jjallaire.shinyapps.io/kmeans-shiny-ojs/
                        - text: "Binning"
                          href: https://jjallaire.shinyapps.io/binning-shiny-ojs/
                        - text: "Data Binding"
                          href: https://jjallaire.shinyapps.io/data-shiny-ojs/
                        - text: "Covid Map"
                          href: https://jjallaire.shinyapps.io/covid19-bicartogram/
            - section: docs/interactive/shiny/index.qmd
              contents:
                - text: "Introduction"
                  href: docs/interactive/shiny/index.qmd
                - docs/interactive/shiny/running.qmd
                - docs/interactive/shiny/execution.qmd
                - docs/interactive/shiny/resources.qmd
                - section: "Examples"
                  contents:
                    - text: "Old Faithful"
                      href: https://jjallaire.shinyapps.io/shiny-old-faithful/
                    - text: "K-Means"
                      href: https://jjallaire.shinyapps.io/shiny-k-means/
                    - text: "Diamonds"
                      href: https://jjallaire.shinyapps.io/shiny-diamonds/
            - section: "Widgets"
              contents:
                - docs/interactive/widgets/jupyter.qmd
                - docs/interactive/widgets/htmlwidgets.qmd
            - docs/interactive/layout.qmd
              
    - id: formats
      title: "Formats"
      contents:
        - section: "HTML"
          contents:
            - docs/output-formats/html-basics.qmd
            - docs/output-formats/html-code.qmd
            - docs/output-formats/html-themes.qmd
            - docs/output-formats/html-publishing.qmd
        - section: "PDF"
          contents:
            - docs/output-formats/pdf-basics.qmd
            - docs/output-formats/pdf-engine.qmd
        - section: "MS Word"
          contents:
            - docs/output-formats/ms-word.qmd
            - docs/output-formats/ms-word-templates.qmd
        - section: "Presentations"
          contents:
            - text: "Overview"
              href: docs/presentations/index.qmd
            - docs/presentations/revealjs/index.qmd
            - docs/presentations/powerpoint.qmd
            - docs/presentations/beamer.qmd
        - section: "Markdown"
          contents:
            - docs/output-formats/gfm.qmd
            - docs/output-formats/hugo.qmd
        - section: "Other"
          contents:
            - docs/output-formats/more-formats.qmd
            
    - id: projects
      title: "Projects"
      contents:
        - section: "Using Projects"
          contents:
            - docs/projects/quarto-projects.qmd
            - docs/projects/code-execution.qmd
            - docs/projects/virtual-environments.qmd
        - section: "Websites"
          contents:
            - docs/websites/website-basics.qmd
            - docs/websites/website-navigation.qmd
            - docs/websites/website-search.qmd
            - docs/websites/website-tools.qmd
            - docs/websites/publishing-websites.qmd
        - section: "Books"
          contents:
            - docs/books/book-basics.qmd
            - docs/books/book-structure.qmd
            - docs/books/book-crossrefs.qmd
            - docs/books/book-output.qmd
            
bibliography: references.bib

format:
  html:
    toc: true
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html

filters:
  - filters/include-files.lua
  
editor: visual



