# Regenerates the download json
name: Update Downloads
on:
  workflow_dispatch:
  schedule:
    - cron:  "*/15 * * * *"
jobs:
  update-downloads:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.auto-commit.outputs.changes_detected }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
#        with:
#          token: ${{ secrets.COMMIT_PAT }}
      - name: Regenerate Download Json
        uses: ./.github/workflows/actions/release-info
        with:
          owner: 'quarto-dev'
          repo: 'quarto-cli'
          out-path: 'docs/download/'
          redirects-path: '_redirects'
          redirects-template: /download/latest/$$prefix$$-$$suffix$$.$$extension$$
          pre-redirects-template: /download/prerelease/$$prefix$$-$$suffix$$.$$extension$$
          github-token: ${{ github.token }}          
      - name: Commit Changes
        id: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: .
          commit_user_name: Github Action Runner
          commit_user_email: runner@quarto.org
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          skip_checkout: true

  publish-changes:
    needs: [ update-downloads ]
    if: ${{ needs.update-downloads.outputs.changes_detected == 'true' }}
    uses: ./.github/workflows/publish.yml